# Config file .travis.yml

language: python

python:
  - "2.7"

env:
  - VERSION="7.0" ODOO_REPO="odoo/odoo" UNIT_TEST=1
  - VERSION="7.0" ODOO_REPO="OCA/OCB" UNIT_TEST=1

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/OCA/reporting-engine ${HOME}/reporting-engine -b ${VERSION}
  - git clone https://github.com/oca/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - git clone https://github.com/OCA/connector $HOME/connector -b ${VERSION}
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly ${VERSION}

script:
  - travis_run_tests

after_success:
  coveralls
