language: python

python:
  - "2.7"

sudo: false
cache: pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
      - python-simplejson
      - python-serial

env:
  global:
  - VERSION="8.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='transbot@odoo-community.org'
  - secure: "XzZzWhiVWXHI+tmcdYH0rPjietxvr1nUXuCRiqnDY3fM0lq6RmtwOlpDDwYEiX+9fHAE8mDttlJ7H4J/YZ+0ugwZxeM10yuT7FwkJY9kPvBe6T59P9aD9R6mSC/da4JGVd+Th5QXDBuBGRBVdY/qBT2lagHuSzBZdKwvMMsaBtA="

  matrix:
  - LINT_CHECK="1"
  - TRANSIFEX="1"
  - TESTS="1" ODOO_REPO="OCA/OCB" EXCLUDE="account_asset_management,account_asset_management_xls,account_journal_always_check_date,account_constraints"
  - TESTS="1" ODOO_REPO="odoo/odoo" EXCLUDE="account_asset_management,account_asset_management_xls,account_journal_always_check_date,account_constraints"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="account_asset_management,account_asset_management_xls"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="account_asset_management,account_asset_management_xls"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="account_journal_always_check_date"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="account_journal_always_check_date"
  - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="account_constraints"
  - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="account_constraints"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/oca/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
