# Config file .travis.yml

language: python

python:
  - "2.7"

env:
  - VERSION="8.0" ODOO_REPO="odoo/odoo" EXCLUDE="account_constraints,account_partner_required,async_move_line_importer,account_move_validation_improvement,account_default_draft_move,account_move_batch_validate"
  - VERSION="8.0" ODOO_REPO="odoo/odoo" INCLUDE="account_constraints,account_move_validation_improvement,account_default_draft_move,account_move_batch_validate"
  - VERSION="8.0" ODOO_REPO="odoo/odoo" INCLUDE="account_partner_required"
  - VERSION="8.0" ODOO_REPO="odoo/odoo" INCLUDE="async_move_line_importer"

  - VERSION="8.0" ODOO_REPO="OCA/OCB"   EXCLUDE="account_constraints, account_partner_required,async_move_line_importer,account_move_validation_improvement,account_default_draft_move,account_move_batch_validate"
  - VERSION="8.0" ODOO_REPO="OCA/OCB"   INCLUDE="account_constraints,account_move_validation_improvement,account_default_draft_move,account_move_batch_validate"
  - VERSION="8.0" ODOO_REPO="OCA/OCB"   INCLUDE="account_partner_required"
  - VERSION="8.0" ODOO_REPO="OCA/OCB" INCLUDE="async_move_line_importer"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/oca/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools -b r2
  #- git clone https://github.com/OCA/connector $HOME/connector -b ${VERSION}
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly ${VERSION}

script:
  - travis_run_flake8
  - travis_run_tests

after_success:
  coveralls
