# Config file .travis.yml

language: python

python:
  - "2.7"

env:
  - VERSION="7.0" ODOO_REPO="odoo/odoo" EXCLUDE="account_constraints,account_partner_required,async_move_line_importer"
  - VERSION="7.0" ODOO_REPO="odoo/odoo" INCLUDE="account_constraints"
  - VERSION="7.0" ODOO_REPO="odoo/odoo" INCLUDE="account_partner_required"
  - VERSION="7.0" ODOO_REPO="odoo/odoo" INCLUDE="async_move_line_importer"

  - VERSION="7.0" ODOO_REPO="OCA/OCB"   EXCLUDE="account_constraints, account_partner_required,async_move_line_importer"
  - VERSION="7.0" ODOO_REPO="OCA/OCB"   INCLUDE="account_constraints"
  - VERSION="7.0" ODOO_REPO="OCA/OCB"   INCLUDE="account_partner_required"
  - VERSION="7.0" ODOO_REPO="odoo/odoo" INCLUDE="async_move_line_importer"


virtualenv:
  system_site_packages: true

install:
 - git clone https://github.com/dreispt/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools -b add-include-env
 - git clone https://github.com/OCA/connector $HOME/connector -b ${VERSION}
 - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
 - travis_install_nightly ${VERSION}
script:
  # - travis_run_flake8
  - travis_run_tests

after_success:
  coveralls
